name: OMERO
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Run integration tests against OMERO
    runs-on: ubuntu-latest
    env:
      STAGE: cli
    steps:
      - uses: actions/checkout@v3
      - name: launch Omero test database
        run: "sudo chmod +x .omero/* && .omero/compose up --detach"
        env:
            ROOTPASS: omero
            POSTGRES_IMAGE: postgres
            POSTGRES_VERSION: 10
            POSTGRES_PASSWORD: postgres
            OMERO_SERVER_IMAGE: openmicroscopy/omero-server
            OMERO_SERVER_VERSION: 5
            OMERO_SERVER_TCP: "4063:"
            OMERO_SERVER_SSL: "4064:"
            OMERO_WEB_IMAGE: openmicroscopy/omero-web-standalone
            OMERO_WEB_VERSION: 5
            OMERO_WEB_PORT: "4080:"
            BUILD_IMAGE: adoptopenjdk:11-jdk-hotspot-bionic
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Build omero_arc
        run: pip install .
      - name: Run tests
        run: pip install pytest omero-py restview mox3 && pytest -v
        env:
          OMERODIR: .
          ICE_CONFIG: test/ice.config
      - name: Stop Omero test database
        run: "sudo .omero/compose down"  