name: OMERO
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Run integration tests against OMERO
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.8"]
    env:
      STAGE: cli
    steps:
      - uses: actions/checkout@v3
      - name: Launch test db
        run: sudo chmod +x .omero/* && .omero/compose up
        env:
          ROOTPASS: omero
          POSTGRES_IMAGE: postgres
          POSTGRES_VERSION: 10
          POSTGRES_PASSWORD: postgres
          OMERO_SERVER_IMAGE: openmicroscopy/omero-server
          OMERO_SERVER_VERSION: 5
          OMERO_SERVER_TCP: "4063:"
          OMERO_SERVER_SSL: "4064:"
          OMERO_WEB_IMAGE: openmicroscopy/omero-web-standalone
          OMERO_WEB_VERSION: 5
          OMERO_WEB_PORT: "4080:"
          BUILD_IMAGE: adoptopenjdk:11-jdk-hotspot-bionic
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 
      - name: Build and run OMERO tests
        run: pip install pytest omero restview mox3 && pytest -v
        env:
          OMERODIR: .
          ICE_CONFIG: test/ice.config